version: "3.8"

services:
  # 1. MongoDB
  mongodb:
    image: mongo:latest
    container_name: ecommerce-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ecommerce_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./database:/docker-entrypoint-initdb.d
    command:
      [
        "bash",
        "-c",
        "chmod +x /docker-entrypoint-initdb.d/init-mongo.sh && docker-entrypoint.sh mongod",
      ]
    networks:
      - ecommerce-network

  # 2. Backend
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://root:password123@mongodb:27017/ecommerce_db?authSource=admin
      JWT_SECRET: 6db15c5140c0b35c261274c2b8b32b569443909518aa37fefc
      SESSION_SECRET: 87e9c61d7a8f4b6a98f1d0a3d2c7e1b4a6f3c8d1f2e0a9b5c7d6f1e3a4b9c0d
      FRONTEND_URL: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: 0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - ecommerce-network

volumes:
  mongo_data:

networks:
  ecommerce-network:
    driver: bridge
